=== practical-works/asp.net-ofppt/XML_TP/XML_TP2/Examen/examen.dtd
<!ELEMENT examen (code-cours, titre, date, questions)>

<!ELEMENT code-cours (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date (mois, annee)>
<!ELEMENT mois (#PCDATA)>
<!ELEMENT annee (#PCDATA)>

<!ELEMENT questions (question, question, question, question, question, question?)>
    <!ELEMENT question (partie+)>
      <!ELEMENT partie ((partie?, texte+)+)>
        <!ELEMENT texte (#PCDATA)>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP2/Examen/examen.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen>
  <code-cours>1</code-cours>
  <titre>Math√©matiques</titre>
  <date>
    <mois>01</mois>
    <annee>1991</annee>
  </date>
  <questions>
    <question>
      <partie>
        <texte>Partie 1</texte>
        <partie>
          <texte>Contenu</texte>
        </partie>
      </partie>
    </question>
  </questions>
</examen>
