=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex3 - Annuaire/annuaire.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="annuaire">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personne" type="personneType" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:positiveInteger"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="personneType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"></xs:element>
      <xs:element name="prenom" type="xs:string"></xs:element>
      <xs:element name="adresse" type="adresseType"></xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="adresseType">
    <xs:sequence>
      <xs:element name="rue" type="xs:string"></xs:element>
      <xs:element name="code-postal" type="xs:positiveInteger"></xs:element>
      <xs:element name="ville" type="xs:string"></xs:element>
      <xs:element name="telephones" type="telephoneCollectionType"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="telephoneCollectionType">
    <xs:sequence>
      <xs:element name="telephone" type="telephoneType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="telephoneType">
    <xs:simpleContent>
      <xs:extension base="xs:positiveInteger">
        <xs:attribute name="type">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="mobile"></xs:enumeration>
              <xs:enumeration value="fixe"></xs:enumeration>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
    
  </xs:complexType>
</xs:schema>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex3 - Annuaire/annuaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<annuaire
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="annuaire.xsd">
	<personne id="1">
		<nom>Nouâman</nom>
		<prenom>Roumaissa</prenom>
		<adresse>
			<rue>DB El amid N°17</rue>
			<code-postal>40050</code-postal>
			<ville>Marrakech</ville>
			<telephones>
				<telephone type="mobile">0678254789</telephone>
				<telephone type="fixe">0598254710</telephone>
			</telephones>
		</adresse>
	</personne>
	<personne id="2">
		<nom>El alami</nom>
		<prenom>Rayan</prenom>
		<adresse>
			<rue>DB El omari N°20</rue>
			<code-postal>10000</code-postal>
			<ville>Marrakech</ville>
			<telephones>
				<telephone type="mobile">0699478299</telephone>
				<telephone type="fixe">0598221459</telephone>
			</telephones>
		</adresse>
	</personne>
</annuaire>
