=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex2 - Livre/livre2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="livre" type="livreType"></xs:element>

  <xs:complexType name="livreType">
    <xs:sequence>
      <xs:element name="auteurs" type="auteursType"></xs:element>
      <xs:element name="sections" type="sectionsType"></xs:element>
    </xs:sequence>
    <xs:attribute name="titre" type="xs:string"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="auteursType">
    <xs:sequence>
      <xs:element name="auteur" type="auteurType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sectionsType">
    <xs:sequence>
      <xs:element name="section" type="sectionType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="auteurType">
    <xs:attribute name="nom" type="xs:string"></xs:attribute>
    <xs:attribute name="prenom" type="xs:string"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="sectionType">
    <xs:sequence>
      <xs:element name="chapitre" type="chapitreType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
    <xs:attribute name="titre" type="xs:string"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="chapitreType">
    <xs:sequence>
      <xs:element name="paragraphe" type="xs:string" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
    <xs:attribute name="titre" type="xs:string"></xs:attribute>
  </xs:complexType>
</xs:schema>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex2 - Livre/livre2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<livre 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="livre2.xsd" 
  titre="livre 2">
	<auteurs>
		<auteur nom="Hamdi" prenom="Mohamed"/>
		<auteur nom="Mahmoud" prenom="Ahmed"/>
	</auteurs>
	<sections>
		<section titre="section 1">
			<chapitre titre="chapitre 1">
				<paragraphe>Exemple de paragraphe</paragraphe>
				<paragraphe>Exemple de paragraphe</paragraphe>
			</chapitre>
			<chapitre titre="chapitre 2">
				<paragraphe>Exemple de paragraphe</paragraphe>
				<paragraphe>Exemple de paragraphe</paragraphe>
			</chapitre>
		</section>
		<section titre="section 2">
			<chapitre titre="chapitre 1">
				<paragraphe>Exemple de paragraphe</paragraphe>
				<paragraphe>Exemple de paragraphe</paragraphe>
			</chapitre>
			<chapitre titre="chapitre 2">
				<paragraphe>Exemple de paragraphe</paragraphe>
				<paragraphe>Exemple de paragraphe</paragraphe>
			</chapitre>
		</section>
	</sections>
</livre>
