=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex4 - Bibliographie/bibliographie.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bibliographie">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="livres" type="livreCollectionType"></xs:element>
        <xs:element name="articles" type="articleCollectionType"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="livreCollectionType">
    <xs:sequence>
      <xs:element name="livre" type="livreType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="articleCollectionType">
    <xs:sequence>
      <xs:element name="article" type="articleType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="titre" type="xs:string"></xs:element>
  <xs:element name="auteur" type="xs:string"></xs:element>
  <xs:element name="avis" type="xs:string"></xs:element>
  
  <xs:complexType name="livreType">
    <xs:sequence>
      <xs:element ref="titre"></xs:element>
      <xs:element ref="auteur" maxOccurs="unbounded"></xs:element>
      <xs:element name="tomes" type="tomeCollectionType"></xs:element>
      <xs:element name="infosEdition" type="infosEditionType"></xs:element>
      <xs:element ref="avis" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="articleType">
    <xs:sequence>
      <xs:element ref="titre"></xs:element>
      <xs:element ref="auteur" maxOccurs="unbounded"></xs:element>
      <xs:element name="infosPublication" type="infosPublicationType"></xs:element>
      <xs:element ref="avis" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tomeCollectionType">
    <xs:sequence>
      <xs:element name="tome" type="tomeType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tomeType">
    <xs:sequence>
      <xs:element name="pages" type="xs:positiveInteger"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="infosEditionType">
    <xs:sequence>
      <xs:element name="editeur" type="xs:string"></xs:element>
      <xs:element name="lieuEdition" type="xs:string"></xs:element>
      <xs:element name="lieuImpression" type="xs:string"></xs:element>
      <xs:element name="ISBN" type="xs:string"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="infosPublicationType">
    <xs:sequence>
      <xs:element name="nomJournal" type="xs:string"></xs:element>
      <xs:element name="pages" type="xs:positiveInteger"></xs:element>
      <xs:element name="anneePublication" type="xs:positiveInteger"></xs:element>
      <xs:element name="numÃ©roJournal" type="xs:positiveInteger"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex4 - Bibliographie/bibliographie.xml
<?xml version="1.0" encoding="utf-8"?>
<bibliographie
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="bibliographie.xsd">
  <livres>
    <livre>
      <titre>Les secrets de l'hunivers</titre>
      <auteur>Charles X</auteur>
      <tomes>
        <tome>
          <pages>10</pages>
        </tome>
        <tome>
          <pages>20</pages>
        </tome>
      </tomes>
      <infosEdition>
        <editeur>Books Home</editeur>
        <lieuEdition>New York</lieuEdition>
        <lieuImpression>New York</lieuImpression>
        <ISBN>4875-7251-4521-7821</ISBN>
      </infosEdition>
      <avis></avis>
    </livre>
  </livres>
  <articles>
    <article>
      <titre>Les 7 éléments</titre>
      <auteur>Karan Jonas</auteur>
      <infosPublication>
        <nomJournal>JouJou</nomJournal>
        <pages>100</pages>
        <anneePublication>1989</anneePublication>
        <numéroJournal>17</numéroJournal>
      </infosPublication>
    </article>
    <article>
      <titre>Les 7 éléments</titre>
      <auteur>Karan Jonas</auteur>
      <infosPublication>
        <nomJournal>JouJou</nomJournal>
        <pages>100</pages>
        <anneePublication>1989</anneePublication>
        <numéroJournal>17</numéroJournal>
      </infosPublication>
      <avis>Un avis facultatif</avis>
    </article>
  </articles>
</bibliographie>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex5 - Bibliographie/bibliographie.xml
<?xml version="1.0" encoding="utf-8"?>
<bibliographie
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="bibliographie.xsd">
  <livres>
    <livre>
      <titre soustitre="les merveilles">Les secrets de l'hunivers</titre>
      <auteur>Charles X</auteur>
      <tomes>
        <tome nbPages="10" sousTitre="Premier tome"/>
        <tome nbPages="20"/>
      </tomes>
      <infosEdition>
        <editeur>Books Home</editeur>
        <lieuEdition>New York</lieuEdition>
        <lieuImpression>New York</lieuImpression>
        <ISBN>4875-7251-4521-7821</ISBN>
      </infosEdition>
      <avis></avis>
    </livre>
  </livres>
  <articles>
    <article>
      <titre>Les 7 éléments</titre>
      <auteur>Karan Jonas</auteur>
      <infosPublication nomJournal="JouJou">
        <pages>100</pages>
        <anneePublication>1989</anneePublication>
        <numéroJournal>17</numéroJournal>
      </infosPublication>
    </article>
    <article>
      <titre>Les 7 éléments</titre>
      <auteur>Karan Jonas</auteur>
      <infosPublication>
        <pages>100</pages>
        <anneePublication>1989</anneePublication>
        <numéroJournal>17</numéroJournal>
      </infosPublication>
      <avis>Un avis facultatif</avis>
    </article>
  </articles>
</bibliographie>
