=== practical-works/asp.net-ofppt/XML_TP/XML_TP2/Arbre/arbre.dtd
<!ELEMENT arbre (A)>
<!ELEMENT A (B, E)>

<!ELEMENT B ((C, F),(C, F),(C, F)+)>
<!ELEMENT C (D?)>
<!ELEMENT F EMPTY>

<!ELEMENT E (D, C, C+)>
<!ELEMENT D EMPTY>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP2/Arbre/arbre.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE arbre SYSTEM "arbre.dtd">
<arbre>
  <A>
    <!-- ====================================================== -->
    <!-- ====================================================== -->
    <B>
      <!-- ====================================================== -->
      <C><D /></C> 
      <F />
      <!-- ====================================================== -->
      <C></C>  
      <F />
      <!-- ====================================================== -->
      <C><D /></C>
      <F />
      <!-- ====================================================== -->
    </B>
    <!-- ====================================================== -->
    <!-- ====================================================== -->
    <E>
      <!-- ====================================================== -->
      <D />
      <!-- ====================================================== -->
      <C><D /></C>
      <!-- ====================================================== -->
      <C></C>
      <!-- ====================================================== -->
    </E>
  </A>
</arbre>
