=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex6 - Examen/examen.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="examen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="code-cours" type="xs:ID"></xs:element>
        <xs:element name="titre" type="xs:string"></xs:element>
        <xs:element name="date" type="dateType"></xs:element>
        <xs:element name="questions" type="questionCollectionType"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="dateType">
    <xs:sequence>
      <xs:element name="mois" type="xs:gMonth"></xs:element>
      <xs:element name="annee" type="xs:gYear"></xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="questionCollectionType">
    <xs:sequence>
      <xs:element name="question" type="questionType" minOccurs="5" maxOccurs="6"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="questionType">
    <xs:sequence>
      <xs:element name="partie" type="partieType" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="partieType" mixed="true">
    <xs:sequence>
      <xs:element name="partie" type="partieType" minOccurs="0" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex6 - Examen/examen.xml
<?xml version="1.0" encoding="utf-8"?>
<examen
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="examen.xsd">
  <code-cours>E1</code-cours>
  <titre>ENF</titre>
  <date>
    <mois>--08</mois>
    <annee>1991</annee>
  </date>
  <questions>
    <question>
      <partie>Partie 1
        <partie>Partie 1-1</partie>Ici le texte de la partie
        <partie>Partie 1-2</partie>Ici le texte de la partie
        <partie>Partie 1-3</partie>Ici le texte de la partie
      </partie>
      <partie>Partie 2
        <partie>Partie 2-1</partie>Ici le texte de la partie
        <partie>Partie 2-2</partie>Ici le texte de la partie
        <partie>Partie 2-3</partie>Ici le texte de la partie
      </partie>
    </question>
    <question>
      <partie>
        Partie 1
        <partie>Partie 1-1</partie>Ici le texte de la partie
        <partie>Partie 1-2</partie>Ici le texte de la partie
        <partie>Partie 1-3</partie>Ici le texte de la partie
      </partie>
      <partie>
        Partie 2
        <partie>Partie 2-1</partie>Ici le texte de la partie
        <partie>Partie 2-2</partie>Ici le texte de la partie
        <partie>Partie 2-3</partie>Ici le texte de la partie
      </partie>
    </question>
    <question>
      <partie>
        Partie 1
        <partie>Partie 1-1</partie>Ici le texte de la partie
        <partie>Partie 1-2</partie>Ici le texte de la partie
        <partie>Partie 1-3</partie>Ici le texte de la partie
      </partie>
      <partie>
        Partie 2
        <partie>Partie 2-1</partie>Ici le texte de la partie
        <partie>Partie 2-2</partie>Ici le texte de la partie
        <partie>Partie 2-3</partie>Ici le texte de la partie
      </partie>
    </question>
    <question>
      <partie>
        Partie 1
        <partie>Partie 1-1</partie>Ici le texte de la partie
        <partie>Partie 1-2</partie>Ici le texte de la partie
        <partie>Partie 1-3</partie>Ici le texte de la partie
      </partie>
      <partie>
        Partie 2
        <partie>Partie 2-1</partie>Ici le texte de la partie
        <partie>Partie 2-2</partie>Ici le texte de la partie
        <partie>Partie 2-3</partie>Ici le texte de la partie
      </partie>
    </question>
    <question>
      <partie>
        Partie 1
        <partie>Partie 1-1</partie>Ici le texte de la partie
        <partie>Partie 1-2</partie>Ici le texte de la partie
        <partie>Partie 1-3</partie>Ici le texte de la partie
      </partie>
      <partie>
        Partie 2
        <partie>Partie 2-1</partie>Ici le texte de la partie
        <partie>Partie 2-2</partie>Ici le texte de la partie
        <partie>Partie 2-3</partie>Ici le texte de la partie
      </partie>
    </question>
  </questions>
</examen>
