=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex1 - Annuaire/annuaire.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="annuaire">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contact" type="contactType" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="contactType">
    <xs:sequence>
      <xs:element name="nom" type="xs:string"></xs:element>
      <xs:element name="prenom" type="xs:string"></xs:element>
      <xs:element name="telephone" type="numerosType" minOccurs="0"></xs:element>
      <xs:element name="email" type="xs:string" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
    <xs:attribute name="titre" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="techno" type="xs:string" use="optional"></xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="numerosType">
    <xs:sequence>
      <xs:element name="indicatif" type="xs:positiveInteger"></xs:element>
      <xs:element name="numero" type="xs:positiveInteger"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== practical-works/asp.net-ofppt/XML_TP/XML_TP3/XML_TP3_Ex1 - Annuaire/annuaire.xml
<?xml version="1.0" encoding="utf-8" ?>
<annuaire
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="annuaire.xsd">
  <contact  titre="..." techno="...">
    <nom>...</nom>
    <prenom>...</prenom>
    <telephone>
      <indicatif>212</indicatif>
      <numero>0612345678</numero>
    </telephone>
    <email>...</email>
    <email>...</email>
  </contact>
  <contact  titre="..." techno="...">
    <nom>...</nom>
    <prenom>...</prenom>
    <telephone>
      <indicatif>212</indicatif>
      <numero>0612345678</numero>
    </telephone>
    <email>...</email>
    <email>...</email>
  </contact>
</annuaire>
